# Generated by Django 4.1.3 on 2022-11-28 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['cname']},
        ),
        migrations.AlterField(
            model_name='category',
            name='cname',
            field=models.CharField(help_text='Enter Category Name', max_length=255, verbose_name='Category Name'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Product Name', max_length=255, verbose_name='Product Name')),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pimage', models.ImageField(upload_to='')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('catergory_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='frontend.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
