# Generated by Django 4.1.3 on 2022-11-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_category_options_alter_category_cname_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catergory_id',
            new_name='catergory',
        ),
    ]
