# Generated by Django 4.1.3 on 2022-12-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_rename_catergory_id_product_catergory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catergory',
            new_name='catergoryid',
        ),
    ]
