# Generated by Django 4.1.3 on 2022-12-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_rename_catergory_product_catergoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pimage',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
