# Generated by Django 4.1.3 on 2022-12-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_product_pimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catergoryid',
            new_name='categoryid',
        ),
    ]
