# Generated by Django 4.1.3 on 2022-12-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_order_alter_product_price_payment_order_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='productname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
